name: ci

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.0.x"
      - name: Restore
        run: dotnet restore SportingClub.sln
      - name: Build
        run: dotnet build SportingClub.sln --configuration Release --no-restore
